name: Dockerized App Deployment
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 24700
          script: |
            cd /root/portfolio_be
            git fetch origin
            git checkout master
            git pull origin master
            
            # 1. Build image (BẮT BUỘC có dấu chấm ở cuối)
            docker build -t portfolio .
            
            # 2. Dọn dẹp container cũ
            docker stop portfolio-container || true
            docker rm portfolio-container || true
            
            # 3. Chạy container mới
            docker run -d --name portfolio-container -p 4000:3000 portfolio